#!/bin/bash
set -e

if [[ $# -lt 1 ]]; then
	echo "Missing EC2 env: {live, dev, stage}!"
    exit 1
fi

# Store params from shell
CMD=$0
PARAMS=$1

# Globals
CWD=`dirname $CMD`
PYTHON=`which python`

function rotate_config() {
	if [[ $# -lt 1 ]]; then
		return 1
	fi

    ec2_env=$1

    if [[ ! -f ${HOME}/.ec2ssh/settings.${ec2_env}.cfg ]]; then
        return 1
    fi

	ln -sf ${HOME}/.ec2ssh/settings.${ec2_env}.cfg ${HOME}/.ec2ssh/settings.cfg
	return $?
}

case "$PARAMS" in
  live)
        rotate_config "LIVE"
        ;;
  west)
        rotate_config "WEST"
        ;;
  dev)
        rotate_config "DEV"
        ;;
  stage)
        rotate_config "STAGE"
        ;;
  *)
        exit 1
        ;;
esac

$PYTHON $CWD/ec2-instances.py
exit 0


